inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

Layout/EndOfLine:
  # Allow both Unix (LF) and Windows (CRLF) line endings
  Enabled: false

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '^\s*#'  # Allow long comments
  Exclude:
    - 'db/seeds.rb'

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'app/controllers/metrics_controller.rb'
    - 'app/controllers/api/v1/users_controller.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'Rakefile'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'app/controllers/metrics_controller.rb'

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'app/controllers/metrics_controller.rb'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'app/controllers/metrics_controller.rb'
    - 'app/controllers/health_controller.rb'
    - 'app/controllers/concerns/exception_handler.rb'
    - 'app/services/user_registration_service.rb'
    - 'app/workers/user_mailer_worker.rb'
    - 'app/models/concerns/auditable.rb'
    - 'db/seeds.rb'

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'app/controllers/metrics_controller.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: percent

Style/WordArray:
  EnforcedStyle: percent

Rails/Output:
  Exclude:
    - 'db/seeds.rb'

Rails/SkipsModelValidations:
  Enabled: false

Rails/I18nLocaleTexts:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/mailers/user_mailer.rb'

Style/HashLikeCase:
  Exclude:
    - 'app/models/concerns/auditable.rb'

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5
  Exclude:
    - 'spec/requests/metrics_spec.rb'

RSpec/AnyInstance:
  Exclude:
    - 'spec/requests/health_spec.rb'
    - 'spec/requests/metrics_spec.rb'

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/**/*'

